name: Build Insights-Proxy Container Images (amd64/arm64)

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [main, 'release/*']

env:
  STABLE_TAG: ${{ github.event_name == 'push' && github.ref_name || format('pr-{0}', github.event.pull_request.number) }}
  EXPIRATION_LABEL: ${{ github.event_name == 'push' && 'insights-proxy.source=github' || 'quay.expires-after=5d' }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME || 'abellott/insights-proxy' }}
  REGISTRY: ${{ vars.REGISTRY || 'quay.io' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        id: clone-repository-amd64
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetches all commits/tags

      - name: Define Release Tag Amd64
        id: define-release-tag-amd64
        shell: bash
        run: echo "RELEASE_TAG_AMD64=$([[ ${GITHUB_REF_NAME} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo ${GITHUB_REF_NAME%.[0-9]*}-amd64 || echo)" >> "$GITHUB_ENV"

      - name: Build Amd64 Insights-Proxy image
        id: build-image-amd64
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          archs: amd64
          tags: ${{ env.STABLE_TAG }}-amd64 ${{ env.STABLE_TAG == 'main' && 'latest-amd64' || '' }} ${{ contains( env.RELEASE_TAG_AMD64 , '.' ) && env.RELEASE_TAG_AMD64 || '' }}
          containerfiles: |
            ./Containerfile
          labels: |
            ${{ env.EXPIRATION_LABEL }}
            insights-proxy.backend.git_sha=${{ github.sha }}

      - name: Push Amd64 To quay.io
        id: push-image-amd64
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.build-image-amd64.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
        continue-on-error: true

      - name: Clone repository
        id: clone-repository-arm64
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetches all commits/tags

      - name: Install qemu dependency
        run: |
           sudo apt-get update
           sudo apt-get install -y qemu-user-static

      - name: Define Release Tag Arm64
        id: define-release-tag-arm64
        shell: bash
        run: echo "RELEASE_TAG_ARM64=$([[ ${GITHUB_REF_NAME} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo ${GITHUB_REF_NAME%.[0-9]*}-arm64 || echo)" >> "$GITHUB_ENV"

      - name: Build Arm64 Insights-Proxy image
        id: build-image-arm64
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          archs: arm64
          tags: ${{ env.STABLE_TAG }}-arm64 ${{ env.STABLE_TAG == 'main' && 'latest-arm64' || '' }} ${{ contains( env.RELEASE_TAG_ARM64 , '.' ) && env.RELEASE_TAG_ARM64 || '' }}
          containerfiles: |
            ./Containerfile
          labels: |
            ${{ env.EXPIRATION_LABEL }}
            insights-proxy.backend.git_sha=${{ github.sha }}

      - name: Push Arm64 To quay.io
        id: push-image-arm64
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.build-image-arm64.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
        continue-on-error: true

